---

- name: Enable Debugging
  debug:
    verbosity: "{{ debuglevel }}"
# Thomas Bludau 20170508
# Might be customized on every customer site
# It is necessary that you have a fix repository,
# otherwhise added systems could have problems
# Requirement is that the systems have access
# to correctly configured repositories.

# figure out where the installation media is. This snippet can either mount it centrally from NFS or unpack it locally
# The following snippet will check if your Hana Install setting is correct and fetches the version of HANA to be installed
# and stores it in hanaversion.
# It may also temporary mounts the installation path or an NFS server that contains the rar-files from SAP SWDC
# Required to run
# => Move to separate role
- include: ./sap-check-media.yml
  tags:
    - hana-install
    - media-check

# => this is the only role that should survive here
- include: ./preconfigure.yml
  tags:
    - hana-install

...
