---

- name: regenerate grub2 conf
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: restart chronyd
  service: name=chronyd state=restarted

- name: restart ntpd
  service: name=ntpd state=restarted

- name: restart systemd-logind
  service: name=systemd-logind state=restarted

# andbuick / 20.07.2017
#
# SAP NOTE 2130510  Version 3 / 28.06.2016 latest Host Agent 7.21
# SAP NOTE 1907566 Version 5 / 27.02.2017 latest documentation
# SAP NOTE 401162 Version 20 / 20.03.2017
# SAP NOTE 1292836 Version 6 / 18.12.2014
# SAP NOTE 1031096 Version 36 / 20.10.2015
#
# Vom SAP Host-Agent werden keine Linux-Kernel-Parameter geändert.
# Service in etc/service/saphostctrl Default Port 1128 SAP HANA & SAP NetWeaver Services SOAP/HTTP
# Service in etc/service/saphostctrls Default Port 1129 SAP HANA & SAP NetWeaver Services SOAP/HTTP
# 
# Starten / Stoppen als Root (root permissions)
# 
# Der Host-Agent muss immer in der aktuellsten Version vorgehalten werden: derzeit 7.21
# Installationsverzeichnis: /usr/sap/hostctrl
# https://wiki.scn.sap.com/wiki/display/ATopics/SAP+Host+Agent+-+Frequently+Asked+Questions
- name: Restart HostAgent
  shell: /usr/sap/hostctrl/exe/saphostexec -restart
  listen: "Execute HANA Host Agent SSL Configuration"


...
