---

- name: disable selinux
  selinux: state=disabled


# TODO: customers may set their own time service, so it may be used to an external role
# this should only do a check, if timing is working
- name: set ntp server via ntpd
  lineinfile: 
    dest: /etc/ntp.conf 
    line: "server {{ ntpserver }} iburst" 
    insertafter: "^server.*"
  notify: restart ntpd
  when: not( (ntpserver is undefined) or (ntpserver is none) or (ntpserver | trim == '') )

- name: enable ntpd
  service: name=ntpd state=started enabled=yes
  when: not( (ntpserver is undefined) or (ntpserver is none) or (ntpserver | trim == '') )

# TODO: instead of deactivating firewall it should configure the firewall according
# to HANA instance number
- name: disable iptables
  service: name=iptables state=stopped enabled=no

- name: disable kdump
  service: name=kdump state=stopped enabled=no
  ignore_errors: True

- name: disable abrt
  service: name=abrtd state=stopped enabled=no
  ignore_errors: True

- name: disable abrt-ccpp
  service: name=abrt-ccpp state=stopped enabled=no
  ignore_errors: True

- name: disable numad
  service: name=numad state=stopped enabled=no
  ignore_errors: True

- name: enable tuned
  service: name=tuned state=started enabled=yes

...
