---

- name: install required packages
  yum: 
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
    - chrony
    - xfsprogs
    - libaio
    - net-tools
    - bind-utils
    - gtk2
    - libicu
    - xulrunner
    - tcsh
    - sudo
    - libssh2
    - expect
    - cairo
    - graphviz
    - iptraf-ng
    - krb5-workstation
    - krb5-libs
    - libpng12
    - nfs-utils
    - lm_sensors
    - rsyslog
    - openssl
    - PackageKit-gtk3-module
    - libcanberra-gtk2
    - libtool-ltdl
    - xorg-x11-xauth
    - numactl
    - tuned
    - tuned-profiles-sap-hana
    - compat-sap-c++-5
    - compat-sap-c++-6

- name: base packages
  yum: state=latest name=@base

- name: required package groups
  yum: 
    state: present 
    name: "{{ packages }}"
  vars:
    packages:
    - "@large-systems"
    - "@network-file-system-client"
    - "@performance"
    - "@compat-libraries"
  when: ( ansible_architecture == "x86_64" )

- name: required package groups
  yum: 
    state: present 
    name: "@compat-libraries"
  when: ( ansible_architecture == "ppc64le" )
    

# Problems with defined state!
#- name: ensure minimum systemd version 219-19.el7_2.4
#  yum: state=present name=systemd-219-19.el7_2.4
#  notify: restart systemd-logind

- name: update system with the latest security fixes
  shell: yum -y update --security warn=no

### TBD:  Now some dependancies need to be checked:
#  RHEL7 und HANA 2.0 => add comapt-sap-c++-5, und noch ein paar weitere 

...
